#!/usr/bin/env bash

hc() {
	herbstclient "$@"
}

hc emit_hook reload

# AUTOSTART #
#-----------#

launch_process() {
	local process="$1"

	pfshot="$(pidof "$process")"
	if [[ "$pfshot" -lt 1 ]]; then
		$process &
	else
		pkill "$process"
		$process &
	fi
}

# Screenshots
launch_process flameshot

launch_process parcellite

launch_process fcitx5

launch_process imwheel

launch_process gentoo-pipewire-launcher
# launch_process pipewire
# launch_process pipewire-pulse
# launch_process wireplumber

# screen effect
# picom -b

xfce4-power-manager &
# to run urxvt properly, we need to read .Xresources.
# xrdb "$HOME/.Xresources" &

# Music player deamon
# mpd --no-daemon $HOME/.config/mpd/mpd.conf &
# mpDris2 -c $HOME/.config/mpDris2/mpDris2.conf &
./panel.sh
nm-applet &
# blueman-manager &
/usr/bin/gnome-keyring-daemon --start --components=secrets

batticon() {
	batt="$(pidof cbatticon)"
	if [[ "$batt" -ge 1 ]]; then
		pkill cbatticon
	fi
	cbatticon --icon-type symbolic --hide-notification /sys/class/power_supply/BAT0 &
}
batticon

# Palse audio control applet
# pa-applet does not work.
volicon() {
	vol="$(pidof pa-applet)"
	if [[ "$vol" -ge 1 ]]; then
		pkill pa-applet
	fi
	"$HOME/.local/bin/pa-applet" &
}
volicon

#$HOME/.config/herbstluftwm/xmobar && herbstclient use_index 1
#sleep 4 && trayer --edge top --align right --widthtype request --padding 3 --iconspacing 5 --SetDockType true --SetPartialStrut true --expand true --monitor 1 --transparent true --alpha 0 --tint 0x181818 --height 20 &

# KEYBINDINGS #
#-------------#
source "$HOME/.config/herbstluftwm/keys"

# THEME #
#-------#
source "$HOME/.config/herbstluftwm/HLWM_themes/theme"

# RULES #
#-------#
source "$HOME/.config/herbstluftwm/winRules"

# Enable screen saver
xscreensaver -no-splash &

sh $HOME/.local/bin/reset_keymap.sh

# do multi monitor setup here, e.g.:
# hc set_monitors 1920x1080+0+0 3840x2160+1920+0
# or simply:
hc detect_monitors

# FIND THE PANEL #
#----------------#
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1); do
	# start it on each monitor
	"$panel" "$monitor" &
done

# Auto startup programs
# Only run at the first time
# Ref: https://herbstluftwm.org/faq.html#firstautostart
if hc silent new_attr bool my_not_first_autostart; then
	slack &
	brave-bin &
	zotero &
	obsidian &
	element-desktop &
	microsoft-edge-stable &
	# After loading, remove rule to define workspace for each startup program.
	sleep 60
	# wait
	hc unrule 'startup'
fi
