#!/usr/bin/env bash

#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

# REMOVE ALL EXISTING KEYBINDINGS #
#---------------------------------#
hc keyunbind --all

# System controls #
#-----------------#
hc keybind $Mod-Control-c spawn urxvt -title logout -e ~/.local/bin/herbst-logout.sh
hc keybind $Mod-Control-r reload
hc keybind $Mod-q close
hc keybind $Mod-Shift-Return spawn "${TERMINAL:-urxvt}" # 
# lock screen
hc keybind $Mod-Control-z spawn i3lock -i ~/Pictures/wallpapers/IMG_0581_1920_1080.PNG

# multimedia #
#------------#
hc keybind XF86MonBrightnessUp spawn xbacklight -inc 10
hc keybind XF86MonBrightnessDown spawn xbacklight -dec 10
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume 0 +5%
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume 0 -5%
hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
# hc keybind XF86AudioPlay spawn playerctl play-pause
hc keybind $Mod-Control-p spawn playerctl play-pause
# hc keybind XF86AudioNext spawn playerctl next
hc keybind $Mod-Control-l spawn playerctl next
# hc keybind XF86AudioPrev spawn playerctl previous
hc keybind $Mod-Control-h spawn playerctl previous
hc keybind $Mod-Control-s spawn playerctl stop
# Volume and Mixer control
hc keybind $Mod-Control-v spawn pavucontrol
hc keybind $Mod-Control-b spawn blueman-manager
hc keybind $Mod-Shift-t spawn spotify

# programs #
# #--------#
# hc keybind $Mod-w spawn bgd
# Check youtube subscribers
# hc keybind $Mod-Control-y spawn ~/.local/scripts/ytsubs.sh
# install to-do for Void or Debian linux
# hc keybind $Mod-Shift-t spawn ~/.local/bin/scratch Todo
hc keybind $Mod-Shift-w spawn urxvt -title windows -e ~/.local/bin/windows.sh
hc keybind $Mod-a spawn urxvt
hc keybind $Mod-t spawn alacritty
hc keybind $Mod-w spawn ~/.cargo/bin/wz
hc keybind $Mod-c spawn ~/.local/bin/conktoggle.sh
# run launchers #
#---------------#
hc keybind $Mod-Control-d spawn dmenu_run -p Launch: -fn "Inconsolata Nerd Font":size=14 -l 10 -nb '#222222' -sb '#007687' -sf '#222222' -nf '#b8b8b8'
hc keybind $Mod-Shift-r spawn rofi -show drun
# no package for rofi-emoji in Gentoo
# hc keybind $Mod-Control-e spawn rofi -show emoji
# Manage virtual machines
hc keybind $Mod-Shift-v spawn urxvt -title vmach.sh -e ~/.local/bin/vmach.sh
# Void linux package manager
# hc keybind $Mod-Shift-i spawn urxvt -title vsp2 -e ~/.local/bin/vsp2
hc keybind $Mod-Shift-d spawn urxvt -title launch.sh -e ~/.local/bin/launch.sh 
hc keybind $Mod-Shift-e spawn urxvt -title configs -e ~/.local/bin/edit_configs.sh
hc keybind $Mod-Control-t spawn urxvt -title themesel.sh -e ~/.local/bin/themesel.sh
hc keybind $Mod-Shift-m spawn slack
hc keybind $Mod-Shift-z spawn zotero

# browsers #
#----------#
hc keybind $Mod-b spawn brave-bin
hc keybind $Mod-Shift-q spawn ~/.local/bin/scratch2 qutebrowser 
# hc keybind $Mod-Shift-n spawn nyxt

hc keybind Print spawn flameshot gui

# scratchpads #
#-------------#
hc keybind $Mod-Return spawn ~/.local/bin/scratch scratchpad 
# FM: file manager
hc keybind $Mod-Shift-f spawn ~/.local/bin/scratch FM
hc keybind $Mod-Shift-a spawn urxvt -title ranger -e ranger
hc keybind $Mod-Control-Return spawn ~/.local/bin/scratchpad
hc keybind $Mod-m spawn ~/.local/bin/scratch Mail
hc keybind $Mod-z spawn ~/.local/bin/scratch Zoom 
# MPD client: ncmpcpp need to configured
# hc keybind $Mod-t spawn scratch Music
hc keybind $Mod-Shift-c spawn ~/.local/bin/scratch2 Calc
# Open kitty terminal
hc keybind $Mod-y spawn ~/.local/bin/scpad

# focusing client #
#-----------------#s
hc keybind $Mod-h  focus left
hc keybind $Mod-j  focus down
hc keybind $Mod-k    focus up
hc keybind $Mod-l focus right

# moving clients in tiling and floating mode #
hc keybind $Mod-Shift-j  shift down
hc keybind $Mod-Shift-k    shift up
hc keybind $Mod-Shift-l shift right
hc keybind $Mod-Shift-h  shift left

# splitting frames #
#------------------#
hc keybind $Mod-u       split   bottom  0.6
hc keybind $Mod-o       split   right   0.6

# let the current frame explode into subframes #
#----------------------------------------------#
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients #
#--------------------------------------#
resizestep=0.02
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# tags #
#------#
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    hc set_layout horizontal
    hc set default_frame_layout 1
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# layouting #
#-----------#
# hc keybind $Mod-Shift-s spawn new-layout.sh 
hc keybind $Mod-Control-x spawn urxvt -title dual_monitor \
  -e ~/.screenlayout/dual_with_LG.sh
hc keybind $Mod-Shift-y spawn ./.local/bin/load-layout.sh
hc keybind $Mod-r remove
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Control-f set_attr clients.focus.floating toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space \
  or , and . compare tags.focus.curframe_wcount = 2 \
  . cycle_layout +1 vertical horizontal max vertical grid \
  , cycle_layout +1

# focus #
#-------#
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-Control-i jumpto urgent

# MOUSE #
#-------#
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize
